(function(){
    
    const _ = require('lodash')

    let allChampions= [
    'Aatrox',
    'Ahri',
    'Akali',
    'Alistar',
    'Amumu',
    'Anivia',
    'Annie',
    'Ashe',
    'AurelionSol',
    'Azir',
    'Bard',
    'Blitzcrank',
    'Brand',
    'Braum',
    'Caitlyn',
    'Camille',
    'Cassiopeia',
    'Chogath',
    'Corki',
    'Darius',
    'Diana',
    'Draven',
    'DrMundo',
    'Ekko',
    'Elise',
    'Evelynn',
    'Ezreal',
    'Fiddlesticks',
    'Fiora',
    'Fizz',
    'Galio',
    'Gangplank',
    'Garen',
    'Gnar',
    'Gragas',
    'Graves',
    'Hecarim',
    'Heimerdinger',
    'Illaoi',
    'Irelia',
    'Ivern',
    'Janna',
    'JarvanIV',
    'Jax',
    'Jayce',
    'Jhin',
    'Jinx',
    'Kaisa',
    'Kalista',
    'Karma',
    'Karthus',
    'Kassadin',
    'Katarina',
    'Kayle',
    'Kayn',
    'Kennen',
    'Khazix',
    'Kindred',
    'Kled',
    'KogMaw',
    'Leblanc',
    'LeeSin',
    'Leona',
    'Lissandra',
    'Lucian',
    'Lulu',
    'Lux',
    'Malphite',
    'Malzahar',
    'Maokai',
    'MasterYi',
    'MissFortune',
    'MonkeyKing',
    'Mordekaiser',
    'Morgana',
    'Nami',
    'Nasus',
    'Nautilus',
    'Nidalee',
    'Nocturne',
    'Nunu',
    'Olaf',
    'Orianna',
    'Ornn',
    'Pantheon',
    'Poppy',
    'Pyke',
    'Quinn',
    'Rakan',
    'Rammus',
    'RekSai',
    'Renekton',
    'Rengar',
    'Riven',
    'Rumble',
    'Ryze',
    'Sejuani',
    'Shaco',
    'Shen',
    'Shyvana',
    'Singed',
    'Sion',
    'Sivir',
    'Skarner',
    'Sona',
    'Soraka',
    'Swain',
    'Syndra',
    'TahmKench',
    'Taliyah',
    'Talon',
    'Taric',
    'Teemo',
    'Thresh',
    'Tristana',
    'Trundle',
    'Tryndamere',
    'TwistedFate',
    'Twitch',
    'Udyr',
    'Urgot',
    'Varus',
    'Vayne',
    'Veigar',
    'Velkoz',
    'Vi',
    'Viktor',
    'Vladimir',
    'Volibear',
    'Warwick',
    'Xayah',
    'Xerath',
    'XinZhao',
    'Yasuo',
    'Yorick',
    'Zac',
    'Zed',
    'Ziggs',
    'Zilean',
    'Zoe',
    'Zyra' 
    ]

    let topChampions = [
    'Aatrox',
    'Akali',
    'Alistar',
    'Camille',
    'Cassiopeia',
    'Chogath',
    'Darius',
    'Diana',
    'DrMundo',
    'Ekko',
    'Fiora',
    'Fizz',
    'Galio',
    'Gangplank',
    'Garen',
    'Gnar',
    'Gragas',
    'Graves',
    'Hecarim',
    'Heimerdinger',
    'Illaoi',
    'Irelia',
    'JarvanIV',
    'Jax',
    'Jayce',
    'Karthus',
    'Kayle',
    'Kennen',
    'Kled',
    'Lissandra',
    'Malphite',
    'Maokai',
    'MonkeyKing',
    'Mordekaiser',
    'Nasus',
    'Nautilus',
    'Olaf',
    'Ornn',
    'Pantheon',
    'Poppy',
    'Quinn',
    'Renekton',
    'Rengar',
    'Riven',
    'Rumble',
    'Ryze',
    'Shyvana',
    'Singed',
    'Sion',
    'Skarner',
    'Swain',
    'TahmKench',
    'Teemo',
    'Trundle',
    'Tryndamere',
    'Udyr',
    'Urgot',
    'Viktor',
    'Vladimir',
    'Yasuo',
    'Yorick',
    ]

    let midChampions = [
    'Ahri',
    'Akali',
    'Anivia',
    'Annie',
    'AurelionSol',
    'Azir',
    'Brand',
    'Cassiopeia',
    'Chogath',
    'Corki',
    'Diana',
    'Ekko',
    'Fizz',
    'Galio',
    'Gangplank',
    'Gragas',
    'Heimerdinger',
    'Irelia',
    'Jayce',
    'Karma',
    'Kassadin',
    'Katarina',
    'Kayle',
    'Khazix',
    'Leblanc',
    'Lissandra',
    'Lucian',
    'Lulu',
    'Lux',
    'Malzahar',
    'Mordekaiser',
    'Morgana',
    'Orianna',
    'Rakan',
    'Rumble',
    'Ryze',
    'Swain',
    'Syndra',
    'Taliyah',
    'Talon',
    'TwistedFate',
    'Veigar',
    'Velkoz',
    'Viktor',
    'Vladimir',
    'Xerath',
    'Yasuo',
    'Zed',
    'Ziggs',
    'Zilean',
    'Zoe',
    'Zyra',
    ]

    let jungleChampions = [
    'Amumu',
    'Chogath',
    'Diana',
    'Elise',
    'Evelynn',
    'Fiddlesticks',
    'Fizz',
    'Gragas',
    'Graves',
    'Hecarim',
    'Ivern',
    'JarvanIV',
    'Jax',
    'Kayle',
    'Kayn',
    'Khazix',
    'Kindred',
    'LeeSin',
    'Maokai',
    'MonkeyKing',
    'Nautilus',
    'Nidalee',
    'Nocturne',
    'Nunu',
    'Olaf',
    'Pantheon',
    'Poppy',
    'Quinn',
    'Rammus',
    'RekSai',
    'Rengar',
    'Riven',
    'Rumble',
    'Sejuani',
    'Shaco',
    'Shyvana',
    'Skarner',
    'Trundle',
    'Twitch',
    'Udyr',
    'Vi',
    'Volibear',
    'Warwick',
    'XinZhao',
    'Zac',
    ]

    const supportChampions = [
    'Alistar',
    'Annie',
    'Bard',
    'Blitzcrank',
    'Brand',
    'Braum',
    'Fiddlesticks',
    'Gragas',
    'Janna',
    'Karma',
    'Kennen',
    'Leona',
    'Lulu',
    'Lux',
    'MissFortune',
    'Morgana',
    'Nami',
    'Nautilus',
    'Ornn',
    'Poppy',
    'Pyke',
    'Rakan',
    'Shen',
    'Sion',
    'Sona',
    'Soraka',
    'TahmKench',
    'Taric',
    'Thresh',
    'Trundle',
    'Velkoz',
    'Volibear',
    'Zilean',
    'Zyra' 
    ]

    const adcChampions = [
    'Ashe',
    'Caitlyn',
    'Corki',
    'Draven',
    'Jhin',
    'Jinx',
    'Kaisa',
    'Kalista',
    'Kayle',
    'Kennen',
    'Kindred',
    'KogMaw',
    'Lucian',
    'MissFortune',
    'Quinn',
    'Sivir',
    'Tristana',
    'Vayne',
    'Xayah',
    'Ziggs',
    ]

    const rTop = () => {
        return _.random( topChampions.length - 1 )
    }

    const rJungle = () => {
        return _.random( jungleChampions.length - 1 )
    }

    const rMid = () => {
        return _.random( midChampions.length - 1 )
    }

    const rSupport = () => {
        return _.random( supportChampions.length - 1 )
    }

    const rAdc = () => {
        return _.random( adcChampions.length - 1 )
    }

    const rAll = () => {
        return _.random( allChampions.length - 1 )
    } 

    console.log( 'Todos:', allChampions[ rAll() ] )
    console.log( '\nTop:', topChampions[ rTop() ] )
    console.log( 'Jungle:', jungleChampions[ rJungle() ] )
    console.log( 'Mid:', midChampions[ rMid() ] )
    console.log( 'Support:', supportChampions[ rSupport() ] )
    console.log( 'Adc:', adcChampions[ rAdc() ] )

})()